### ISSUE TITLE
Support the ability to provide a test yaml file configured using the --config parameter CLI

### ISSUE THREAD

**Issue by eyalke** [aquasecurity/windows-bench#80]
Support the ability to give a specific configuration file to windows-bench CLI , same as we do for bench-common.
Whenever the --config is present, windows-bench won't run the built-in tests but only use the yaml filename tests 

E.g., 
windows-bench.exe --json --outputfile "C:\Program Files\AquaSec\tmp\windowsbench_yFFRnHRL.json" --config "C:\Program Files\AquaSec\tmp\windowsbench_cfg_yFFRnHRL.yaml"

**Comment by chen-keinan** [comment]
@afdesk please have a look at this issue

**Comment by afdesk** [comment]
@eyalke I'm on this issue right now. try to resolve it in a few days. 

as a workaround there is a flag `config-dir` right now.
